//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bandwidth.Net.Test.Iris {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Xml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Xml() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bandwidth.Net.Test.Iris.Xml", typeof(Xml).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;AccountResponse&gt;&lt;Account&gt;&lt;AccountId&gt;14&lt;/AccountId&gt;&lt;CompanyName&gt;CWI Hosting&lt;/CompanyName&gt;&lt;AccountType&gt;Business&lt;/AccountType&gt;&lt;NenaId&gt;&lt;/NenaId&gt;&lt;Tiers&gt;&lt;Tier&gt;0&lt;/Tier&gt;&lt;/Tiers&gt;&lt;Address&gt;&lt;HouseNumber&gt;60&lt;/HouseNumber&gt;&lt;HouseSuffix&gt;&lt;/HouseSuffix&gt;&lt;PreDirectional&gt;&lt;/PreDirectional&gt;&lt;StreetName&gt;Pine&lt;/StreetName&gt;&lt;StreetSuffix&gt;St&lt;/StreetSuffix&gt;&lt;PostDirectional&gt;&lt;/PostDirectional&gt;&lt;AddressLine2&gt;&lt;/AddressLine2&gt;&lt;City&gt;Denver&lt;/City&gt;&lt;StateCode&gt;CO&lt;/StateCode&gt;&lt;Zip&gt;80016&lt;/Zip&gt;&lt;PlusFour&gt;&lt;/PlusFour&gt;&lt;Country&gt;United States&lt;/Country&gt;&lt;Addres [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;SearchResultForAvailableNpaNxx&gt;
        ///
        ///&lt;AvailableNpaNxxList&gt;
        ///
        ///&lt;AvailableNpaNxx&gt;
        ///
        ///&lt;City&gt;NASHVILLE&lt;/City&gt;
        ///
        ///&lt;Npa&gt;252&lt;/Npa&gt;
        ///
        ///&lt;Nxx&gt;220&lt;/Nxx&gt;
        ///
        ///&lt;Quantity&gt;1&lt;/Quantity&gt;
        ///
        ///&lt;State&gt;NC&lt;/State&gt;
        ///
        ///&lt;/AvailableNpaNxx&gt;
        ///
        ///&lt;AvailableNpaNxx&gt;
        ///
        ///&lt;City&gt;FARMVILLE&lt;/City&gt;
        ///
        ///&lt;Npa&gt;252&lt;/Npa&gt;
        ///
        ///&lt;Nxx&gt;228&lt;/Nxx&gt;
        ///
        ///&lt;Quantity&gt;1&lt;/Quantity&gt;
        ///
        ///&lt;State&gt;NC&lt;/State&gt;
        ///
        ///&lt;/AvailableNpaNxx&gt;
        ///
        ///&lt;/AvailableNpaNxxList&gt;
        ///
        ///&lt;/SearchResultForAvailableNpaNxx&gt;.
        /// </summary>
        public static string AvailableNpaNxx {
            get {
                return ResourceManager.GetString("AvailableNpaNxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;SearchResult&gt;&lt;ResultCount&gt;2&lt;/ResultCount&gt;&lt;TelephoneNumberDetailList&gt;&lt;TelephoneNumberDetail&gt;&lt;City&gt;JERSEY CITY&lt;/City&gt;&lt;LATA&gt;224&lt;/LATA&gt;&lt;RateCenter&gt;JERSEYCITY&lt;/RateCenter&gt;&lt;State&gt;NJ&lt;/State&gt;&lt;TelephoneNumber&gt;2012001555&lt;/TelephoneNumber&gt;&lt;/TelephoneNumberDetail&gt;&lt;TelephoneNumberDetail&gt;&lt;City&gt;JERSEY CITY&lt;/City&gt;&lt;LATA&gt;224&lt;/LATA&gt;&lt;RateCenter&gt;JERSEYCITY&lt;/RateCenter&gt;&lt;State&gt;NJ&lt;/State&gt;&lt;TelephoneNumber&gt;123123123&lt;/TelephoneNumber&gt;&lt;/TelephoneNumberDetail&gt;&lt;/TelephoneNumberDetailList&gt;&lt;/SearchResult&gt;.
        /// </summary>
        public static string AvailableNumber {
            get {
                return ResourceManager.GetString("AvailableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;CityResponse&gt;&lt;ResultCount&gt;2&lt;/ResultCount&gt;&lt;Cities&gt;&lt;City&gt;&lt;RcAbbreviation&gt;SOUTHEPINS&lt;/RcAbbreviation&gt;&lt;Name&gt;ABERDEEN&lt;/Name&gt;&lt;/City&gt;&lt;City&gt;&lt;RcAbbreviation&gt;JULIAN&lt;/RcAbbreviation&gt;&lt;Name&gt;ADVANCE&lt;/Name&gt;&lt;/City&gt;&lt;/Cities&gt;&lt;/CityResponse&gt;.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;CoveredRateCenters&gt;&lt;CoveredRateCenter&gt;&lt;Abbreviation&gt;ACME&lt;/Abbreviation&gt;&lt;Name&gt;ACME&lt;/Name&gt;&lt;/CoveredRateCenter&gt;&lt;/CoveredRateCenters&gt;.
        /// </summary>
        public static string CoveredRateCenter {
            get {
                return ResourceManager.GetString("CoveredRateCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;TNs&gt;&lt;TotalCount&gt;4&lt;/TotalCount&gt;&lt;Links&gt;&lt;first&gt;&lt;/first&gt;&lt;/Links&gt;&lt;TelephoneNumbers&gt;&lt;Count&gt;2&lt;/Count&gt;&lt;TelephoneNumber&gt;4158714245&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;4352154439&lt;/TelephoneNumber&gt;&lt;/TelephoneNumbers&gt;&lt;/TNs&gt;.
        /// </summary>
        public static string DiscNumber {
            get {
                return ResourceManager.GetString("DiscNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;Quantity&gt;&lt;Count&gt;2&lt;/Count&gt;&lt;/Quantity&gt;.
        /// </summary>
        public static string DiscNumberTotals {
            get {
                return ResourceManager.GetString("DiscNumberTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;DldaOrderResponse&gt;&lt;DldaOrder&gt;&lt;CustomerOrderId&gt;5a88d16d-f8a9-45c5-a5db-137d700c6a22&lt;/CustomerOrderId&gt;&lt;OrderCreateDate&gt;2014-07-10T12:38:11.833Z&lt;/OrderCreateDate&gt;&lt;AccountId&gt;14&lt;/AccountId&gt;&lt;CreatedByUser&gt;jbm&lt;/CreatedByUser&gt;&lt;OrderId&gt;ea9e90c2-77a4-4f82-ac47-e1c5bb1311f4&lt;/OrderId&gt;&lt;LastModifiedDate&gt;2014-07-10T12:38:11.833Z&lt;/LastModifiedDate&gt;&lt;ProcessingStatus&gt;RECEIVED&lt;/ProcessingStatus&gt;&lt;DldaTnGroups&gt;&lt;DldaTnGroup&gt;&lt;TelephoneNumbers&gt;&lt;TelephoneNumber&gt;2053778335&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;2053865784&lt;/TelephoneNumb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dlda {
            get {
                return ResourceManager.GetString("Dlda", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;OrderHistoryWrapper&gt;&lt;OrderHistory&gt;&lt;OrderDate&gt;2014-05-20T14:21:43.937Z&lt;/OrderDate&gt;&lt;Note&gt;Order backordered - awaiting additional numbers&lt;/Note&gt;&lt;Status&gt;BACKORDERED&lt;/Status&gt;&lt;/OrderHistory&gt;&lt;OrderHistory&gt;&lt;OrderDate&gt;2014-05-20T14:24:43.428Z&lt;/OrderDate&gt;&lt;Note&gt;Order backordered - awaiting additional numbers&lt;/Note&gt;&lt;Author&gt;System&lt;/Author&gt;&lt;Status&gt;BACKORDERED&lt;/Status&gt;&lt;Difference&gt;&lt;/Difference&gt;&lt;/OrderHistory&gt;&lt;/OrderHistoryWrapper&gt;.
        /// </summary>
        public static string DldaHistory {
            get {
                return ResourceManager.GetString("DldaHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;ResponseSelectWrapper&gt;&lt;ListOrderIdUserIdDate&gt;&lt;TotalCount&gt;3&lt;/TotalCount&gt;&lt;OrderIdUserIdDate&gt;&lt;accountId&gt;14&lt;/accountId&gt;&lt;CountOfTNs&gt;2&lt;/CountOfTNs&gt;&lt;userId&gt;team_ua&lt;/userId&gt;&lt;lastModifiedDate&gt;2014-07-07T10:06:43.427Z&lt;/lastModifiedDate&gt;&lt;OrderType&gt;dlda&lt;/OrderType&gt;&lt;OrderDate&gt;2014-07-07T10:06:43.427Z&lt;/OrderDate&gt;&lt;orderId&gt;37a6447c-1a0b-4be9-ba89-3f5cb0aea142&lt;/orderId&gt;&lt;OrderStatus&gt;FAILED&lt;/OrderStatus&gt;&lt;/OrderIdUserIdDate&gt;&lt;OrderIdUserIdDate&gt;&lt;accountId&gt;14&lt;/accountId&gt;&lt;CountOfTNs&gt;2&lt;/CountOfTNs&gt;&lt;userId&gt;team_ua&lt;/userId&gt;&lt;lastModi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DldaList {
            get {
                return ResourceManager.GetString("DldaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;SiteHostsResponse&gt;&lt;SiteHosts&gt; &lt;SiteHost&gt; &lt;SiteId&gt;{id}&lt;/SiteId&gt; &lt;SipPeerHosts&gt; &lt;SipPeerHost&gt; &lt;SipPeerId&gt;{id}&lt;/SipPeerId&gt; &lt;SmsHosts&gt; &lt;Host&gt; &lt;HostName&gt;{IP | host name}&lt;/HostName&gt; &lt;Port&gt;8888&lt;/Port&gt; &lt;/Host&gt;&lt;/SmsHosts&gt; &lt;VoiceHosts&gt;&lt;/VoiceHosts&gt; &lt;TerminationHosts&gt;&lt;/TerminationHosts&gt; &lt;/SipPeerHost&gt;&lt;/SipPeerHosts&gt;&lt;/SiteHost&gt;&lt;/SiteHosts&gt;&lt;/SiteHostsResponse&gt;.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;TNs&gt;&lt;TotalCount&gt;59&lt;/TotalCount&gt;&lt;Links&gt;&lt;first&gt; ( a link goes here ) &lt;/first&gt;&lt;/Links&gt;&lt;TelephoneNumbers&gt;&lt;Count&gt;59&lt;/Count&gt;&lt;TelephoneNumber&gt;8043024183&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8042121778&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8042146066&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8043814903&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8043814905&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8043814864&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8043326094&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8042121771&lt;/TelephoneNumber&gt;&lt;TelephoneNumber&gt;8043024182&lt;/Tele [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InserviceNumberList {
            get {
                return ResourceManager.GetString("InserviceNumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;Quantity&gt;&lt;Count&gt;3&lt;/Count&gt;&lt;/Quantity&gt;.
        /// </summary>
        public static string InserviceNumberTotals {
            get {
                return ResourceManager.GetString("InserviceNumberTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;Notes&gt;&lt;Note&gt;&lt;Id&gt;11299&lt;/Id&gt;&lt;UserId&gt;customer&lt;/UserId&gt;&lt;Description&gt;Test&lt;/Description&gt;&lt;LastDateModifier&gt;2014-11-20T07:08:47.000Z&lt;/LastDateModifier&gt;&lt;/Note&gt;&lt;Note&gt;&lt;Id&gt;11301&lt;/Id&gt;&lt;UserId&gt;customer&lt;/UserId&gt;&lt;Description&gt;Test1&lt;/Description&gt;&lt;LastDateModifier&gt;2014-11-20T07:11:36.000Z&lt;/LastDateModifier&gt;&lt;/Note&gt;&lt;/Notes&gt;.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
    }
}
